### ISSUE TITLE
利用 docker + rancher 来部署前后端分离

### ISSUE THREAD

**Issue by zysam** [zysam/blog#22]
：在开发环境下实践 :)
### nginx 作为静态服务器

``` yml
nginx:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: nginx:1.11-alpine
  volumes:
  - /e/www:/www
  - /e/docker/nginx/conf.d:/etc/nginx/conf.d
  stdin_open: true
```

/www 放置前端打包好的静态文件
/conf.d 目录放置 server.conf 服务配置

server.conf

``` conf
server {
 listen 80 default_server;
 listen [::]:80 default_server ipv6only=on;

 root /www/app;
 index index.html index.htm;

 # Make site accessible from http://localhost/
 server_name localhost;

 location / {
     # First attempt to serve request as file, then
     # as directory, then fall back to displaying a 404.
     # angular 中任意路由都指向 /index.html 不会报 404 找不到啦！
     try_files $uri $uri/ /index.html =404;
     # Uncomment to enable naxsi on this location
     # include /etc/nginx/naxsi.rules
 }
}
```
### rancher 的 ha 作为反向代理

``` yml
ha-9080:
  ports:
  - 9080:9080
  labels:
    io.rancher.loadbalancer.target.apiServer: /api=4800
    io.rancher.scheduler.affinity:host_label: name=sam
    io.rancher.loadbalancer.target.nginx: '80'
  tty: true
  image: rancher/load-balancer-service
  links:
  - apiServer:apiServer
  - nginx:nginx
  stdin_open: true
```

这种就把  /api 转到 apiServer 里，非 /api 的转发的 nginx 服务器 

使用 nodejs + nginx 可以参考这篇：http://blog.fens.me/angularjs-url/
